/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/core/useGLTF";
import ModelPath from "./gladiador.glb";

export default function Gladiador(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(ModelPath);
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Gladiator_weapon.geometry}
        material={materials.Weapon}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.Gladiator.geometry}
        material={materials.Gladiator1}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.01, 0.01, 0.01]}
      />
    </group>
  );
}

useGLTF.preload(ModelPath);
